#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
if rg -n '\b(sorry|axiom|admit)\b' --glob '*.lean' NewLang NewLang.lean; then
  echo 'Unexpected proof placeholder or added axiom in project Lean sources.' >&2
  exit 1
else
  status=$?
  if [ "$status" -ne 1 ]; then exit "$status"; fi
fi
lake build
check_file=$(mktemp --suffix=.lean)
trap 'rm -f "$check_file"' EXIT
printf 'import NewLang\n' > "$check_file"
declarations=(
  NewLang.F0.wellFormed_surviving_dependencies_live
  NewLang.F0.empty_wellFormed
  NewLang.F0.replace_preserves_wellFormed
  NewLang.F0.replace_preserves_incarnation
  NewLang.F0.replace_preserves_governingDomain
  NewLang.F0.replace_preserves_place_and_location
  NewLang.F0.replace_preserves_other_locations
  NewLang.F0.replace_preserves_package_data_and_domains
  NewLang.F0.replace_creates_fresh_current_fact
  NewLang.F0.replace_history_monotone
  NewLang.F0.replace_old_fact_remains_used
  NewLang.F0.replace_old_package_survives_as_loose
  NewLang.F0.replace_new_package_installed
  NewLang.F0.rawReplace_old_current_fact_not_live
  NewLang.F0.replace_rejects_surviving_old_current_dependency
  NewLang.F0.replace_rejects_incoming_old_current_dependency
  NewLang.F0.replace_rejects_previously_used_fact
  NewLang.F0.Counterexample.Replace.before_wellFormed
  NewLang.F0.Counterexample.Replace.independent_replace_is_legal
  NewLang.F0.Counterexample.Replace.unchecked_replace_launders_old_dependency
  NewLang.F0.Counterexample.Replace.old_dependency_is_rejected
  NewLang.F0.Counterexample.Replace.incoming_dependency_is_rejected
  NewLang.F0.Counterexample.Replace.currently_dead_is_not_historically_fresh
  NewLang.F0.RawStore.target_after
  NewLang.F0.RawStore.packages_unchanged
  NewLang.F0.RawStore.incoming_ne_old
  NewLang.F0.RawStore.newFact_ne_old
  NewLang.F0.store_history_monotone
  NewLang.F0.store_preserves_wellFormed
  NewLang.F0.store_preserves_incarnation
  NewLang.F0.store_preserves_governingDomain
  NewLang.F0.store_preserves_place_and_location
  NewLang.F0.store_preserves_other_locations
  NewLang.F0.store_preserves_package_data_and_domains
  NewLang.F0.store_creates_fresh_current_fact
  NewLang.F0.store_old_fact_remains_used
  NewLang.F0.store_new_package_installed
  NewLang.F0.rawStore_old_package_does_not_survive
  NewLang.F0.store_old_package_does_not_survive
  NewLang.F0.store_other_survivors_preserved
  NewLang.F0.rawStore_old_current_fact_not_live
  NewLang.F0.store_rejects_other_surviving_old_current_dependency
  NewLang.F0.store_rejects_incoming_old_current_dependency
  NewLang.F0.store_requires_discardable_old_package
  NewLang.F0.store_rejects_nondiscardable_old_package
  NewLang.F0.store_rejects_previously_used_fact
  NewLang.F0.Counterexample.Store.before_wellFormed
  NewLang.F0.Counterexample.Store.store_can_eliminate_old_only_dependency
  NewLang.F0.Counterexample.Store.old_self_dependency_rejects_replace_but_allows_store
  NewLang.F0.Counterexample.Store.old_only_dependency_removed_from_validation
  NewLang.F0.Counterexample.Store.incoming_need_not_be_discardable
  NewLang.F0.Counterexample.Store.other_survivor_dependency_is_rejected
  NewLang.F0.Counterexample.Store.incoming_dependency_is_rejected
  NewLang.F0.Counterexample.Store.nondiscardable_old_package_is_rejected
  NewLang.F0.Counterexample.Store.unchecked_other_dependency_breaks_candidate
  NewLang.F0.Counterexample.Store.unchecked_discardability_silently_loses_package
  NewLang.F0.Counterexample.Store.currently_dead_fact_cannot_be_reused
  NewLang.F0.swap_same_is_identity
  NewLang.F0.swap_same_preserves_history
  NewLang.F0.swap_same_preserves_current_fact
  NewLang.F0.swap_same_preserves_package
  NewLang.F0.same_swap_is_legal
  NewLang.F0.RawSwapDistinct.targets_after
  NewLang.F0.RawSwapDistinct.packages_distinct
  NewLang.F0.RawSwapDistinct.places_distinct
  NewLang.F0.swap_distinct_preserves_wellFormed
  NewLang.F0.swap_distinct_preserves_incarnations
  NewLang.F0.swap_distinct_preserves_governingDomains
  NewLang.F0.swap_distinct_preserves_places_and_locations
  NewLang.F0.swap_distinct_exchanges_packages
  NewLang.F0.swap_distinct_both_packages_survive
  NewLang.F0.swap_distinct_preserves_loose_packages
  NewLang.F0.swap_distinct_preserves_package_data_and_domains
  NewLang.F0.swap_distinct_preserves_other_locations
  NewLang.F0.swap_distinct_history_monotone
  NewLang.F0.swap_distinct_creates_two_fresh_current_facts
  NewLang.F0.swap_distinct_old_facts_remain_used
  NewLang.F0.swap_distinct_survivors_preserved
  NewLang.F0.rawSwapDistinct_old_left_fact_not_live
  NewLang.F0.rawSwapDistinct_old_right_fact_not_live
  NewLang.F0.swap_rejects_surviving_old_current_dependency
  NewLang.F0.swap_rejects_left_self_current_dependency
  NewLang.F0.swap_rejects_left_package_cross_dependency
  NewLang.F0.swap_rejects_right_self_current_dependency
  NewLang.F0.swap_rejects_right_package_cross_dependency
  NewLang.F0.swap_rejects_reused_left_fact
  NewLang.F0.swap_rejects_reused_right_fact
  NewLang.F0.swap_rejects_colliding_new_facts
  NewLang.F0.Counterexample.Swap.before_wellFormed
  NewLang.F0.Counterexample.Swap.independent_distinct_swap_is_legal
  NewLang.F0.Counterexample.Swap.swap_does_not_require_discardable
  NewLang.F0.Counterexample.Swap.same_place_swap_preserves_self_dependency
  NewLang.F0.Counterexample.Swap.left_self_dependency_is_rejected
  NewLang.F0.Counterexample.Swap.right_self_dependency_is_rejected
  NewLang.F0.Counterexample.Swap.left_cross_dependency_is_rejected
  NewLang.F0.Counterexample.Swap.right_cross_dependency_is_rejected
  NewLang.F0.Counterexample.Swap.self_dependency_allows_same_swap_but_rejects_distinct_swap
  NewLang.F0.Counterexample.Swap.swap_rejects_cyclic_dependency_laundering
  NewLang.F0.Counterexample.Swap.third_survivor_left_dependency_is_rejected
  NewLang.F0.Counterexample.Swap.third_survivor_right_dependency_is_rejected
  NewLang.F0.Counterexample.Swap.unchecked_cyclic_swap_breaks_dependencies
  NewLang.F0.Counterexample.Swap.historical_reuse_and_pair_collision_are_rejected
  NewLang.F0.replace_preserves_incarnation_history
  NewLang.F0.store_preserves_incarnation_history
  NewLang.F0.swap_same_preserves_incarnation_history
  NewLang.F0.swap_distinct_preserves_incarnation_history
  NewLang.F0.RawInitialize.target_after
  NewLang.F0.initialize_preserves_wellFormed
  NewLang.F0.initialize_consumes_vacancy
  NewLang.F0.initialize_installs_package
  NewLang.F0.initialize_package_unique_installed_carrier
  NewLang.F0.initialize_incarnation_history_monotone
  NewLang.F0.initialize_value_fact_history_monotone
  NewLang.F0.initialize_creates_fresh_incarnation
  NewLang.F0.initialize_creates_fresh_current_fact
  NewLang.F0.initialize_creates_governing_relation
  NewLang.F0.initialize_uses_stable_site_place
  NewLang.F0.initialize_preserves_other_locations
  NewLang.F0.initialize_preserves_package_data
  NewLang.F0.initialize_preserves_live_domains
  NewLang.F0.initialize_rejects_reused_incarnation
  NewLang.F0.initialize_rejects_reused_current_fact
  NewLang.F0.initialize_rejects_dead_domain
  NewLang.F0.initialize_rejects_missing_authority
  NewLang.F0.take_preserves_wellFormed
  NewLang.F0.take_restores_vacancy
  NewLang.F0.take_preserves_other_locations
  NewLang.F0.take_preserves_package_data
  NewLang.F0.take_preserves_live_domains
  NewLang.F0.take_preserves_identity_histories
  NewLang.F0.take_ended_identities_remain_recorded
  NewLang.F0.take_ends_incarnation
  NewLang.F0.take_old_current_fact_not_live
  NewLang.F0.take_ends_governing_relation
  NewLang.F0.take_does_not_finalize_domain
  NewLang.F0.take_rejects_wrong_ending_domain
  NewLang.F0.take_rejects_missing_authority
  NewLang.F0.destroy_preserves_wellFormed
  NewLang.F0.destroy_restores_vacancy
  NewLang.F0.destroy_preserves_other_locations
  NewLang.F0.destroy_preserves_package_data
  NewLang.F0.destroy_preserves_live_domains
  NewLang.F0.destroy_preserves_identity_histories
  NewLang.F0.destroy_ended_identities_remain_recorded
  NewLang.F0.destroy_ends_incarnation
  NewLang.F0.destroy_old_current_fact_not_live
  NewLang.F0.destroy_ends_governing_relation
  NewLang.F0.destroy_does_not_finalize_domain
  NewLang.F0.destroy_rejects_wrong_ending_domain
  NewLang.F0.destroy_rejects_missing_authority
  NewLang.F0.take_old_package_survives_as_loose
  NewLang.F0.take_old_package_unique_loose_carrier
  NewLang.F0.take_survivors_preserved
  NewLang.F0.take_rejects_surviving_old_current_dependency
  NewLang.F0.take_rejects_old_self_current_dependency
  NewLang.F0.destroy_old_package_does_not_survive
  NewLang.F0.destroy_other_survivors_preserved
  NewLang.F0.destroy_rejects_other_surviving_old_current_dependency
  NewLang.F0.destroy_requires_discardable_old_package
  NewLang.F0.destroy_rejects_nondiscardable_old_package
  NewLang.F0.Counterexample.Lifetime.before_wellFormed
  NewLang.F0.Counterexample.Lifetime.independent_take_is_legal
  NewLang.F0.Counterexample.Lifetime.take_accepts_nondiscardable_value
  NewLang.F0.Counterexample.Lifetime.take_preserves_domain_live_dependency
  NewLang.F0.Counterexample.Lifetime.independent_destroy_is_legal
  NewLang.F0.Counterexample.Lifetime.destroy_can_eliminate_old_only_dependency
  NewLang.F0.Counterexample.Lifetime.old_self_dependency_rejects_take_but_allows_destroy
  NewLang.F0.Counterexample.Lifetime.third_survivor_rejects_take
  NewLang.F0.Counterexample.Lifetime.third_survivor_rejects_destroy
  NewLang.F0.Counterexample.Lifetime.nondiscardable_destroy_is_rejected
  NewLang.F0.Counterexample.Lifetime.unchecked_destroy_without_discardability_loses_nondiscardable_package
  NewLang.F0.Counterexample.Lifetime.unchecked_take_breaks_dependencies
  NewLang.F0.Counterexample.Lifetime.unchecked_destroy_third_dependency_breaks_candidate
  NewLang.F0.Counterexample.Lifetime.initialize_accepts_nondiscardable_value
  NewLang.F0.Counterexample.Lifetime.initialize_then_take_conserves_occupancy_responsibility
  NewLang.F0.Counterexample.Lifetime.reinitialize_same_location_uses_fresh_incarnation
  NewLang.F0.Counterexample.Lifetime.dead_historical_incarnation_cannot_be_reused
  NewLang.F0.Counterexample.Lifetime.historical_value_fact_reuse_is_rejected
  NewLang.F0.Counterexample.Lifetime.wrong_domain_and_missing_authority_are_rejected
  NewLang.F0.Counterexample.Lifetime.dead_domain_and_missing_initialize_authority_are_rejected
  NewLang.F0.acquire_ref_targets_exact_location_incarnation
  NewLang.F0.acquire_ref_implies_live_incarnation
  NewLang.F0.acquire_ref_matches_governing_domain
  NewLang.F0.acquire_ref_implies_governing_relation
  NewLang.F0.acquire_ref_implies_live_domain
  NewLang.F0.acquire_ref_rejects_missing_stability_evidence
  NewLang.F0.acquire_ref_rejects_missing_access_or_provenance_premise
  NewLang.F0.acquire_ref_rejects_wrong_domain
  NewLang.F0.acquire_ref_rejects_incarnation_mismatch
  NewLang.F0.ended_incarnation_cannot_acquire_ref
  NewLang.F0.initialize_yields_current_ptr
  NewLang.F0.initialize_ptr_can_acquire_ref
  NewLang.F0.reinitialize_does_not_revive_old_ptr
  NewLang.F0.stale_ptr_after_take_cannot_acquire_ref
  NewLang.F0.stale_ptr_after_destroy_cannot_acquire_ref
  NewLang.F0.take_then_reinitialize_does_not_revive_old_ptr
  NewLang.F0.destroy_then_reinitialize_does_not_revive_old_ptr
  NewLang.F0.ptr_remains_live_across_current_value_replace
  NewLang.F0.Counterexample.Reference.initialized_ptr_is_safely_issued_and_acquires_ref
  NewLang.F0.Counterexample.Reference.take_stale_ptr_contrast
  NewLang.F0.Counterexample.Reference.destroy_stale_ptr_contrast
  NewLang.F0.Counterexample.Reference.same_site_reinitialize_old_ptr_rejected_new_ptr_accepted
  NewLang.F0.Counterexample.Reference.same_site_destroy_reinitialize_old_ptr_rejected_new_ptr_accepted
  NewLang.F0.Counterexample.Reference.missing_stability_wrong_domain_and_missing_access_are_rejected
  NewLang.F0.Counterexample.Reference.replace_changes_current_fact_but_same_ptr_acquires_ref
  NewLang.F0.Counterexample.Reference.omitting_only_incarnation_freshness_revives_stale_ptr
  NewLang.F0.Counterexample.Reference.omitting_incarnation_match_accepts_old_ptr_after_fresh_reinitialize
  NewLang.F0.Counterexample.Reference.omitting_domain_match_accepts_wrong_live_domain
  NewLang.F0.Counterexample.Domain.simple_domain_transfer_is_legal
  NewLang.F0.Counterexample.Domain.governed_root_allows_transfer_but_rejects_finalization
  NewLang.F0.Counterexample.Domain.DomainLive_dependency_allows_transfer_but_rejects_finalization
  NewLang.F0.Counterexample.Domain.independent_domain_finalization_is_legal
  NewLang.F0.Counterexample.Domain.one_carrier_may_hold_multiple_domain_identities
  NewLang.F0.Counterexample.Domain.transfer_with_root_and_dependency_preserves_acquisition
  NewLang.F0.Counterexample.Domain.unchecked_finalization_strands_governed_root_only
  NewLang.F0.Counterexample.Domain.unchecked_finalization_strands_domain_dependency_only
  NewLang.F0.Counterexample.Domain.ending_root_allows_later_domain_finalization
  NewLang.F0.Counterexample.Domain.broken_identity_rename_can_preserve_wellFormed
  NewLang.F0.Counterexample.Domain.missing_permissions_and_wrong_carriers_are_rejected
  NewLang.F0.Counterexample.Domain.dead_domain_cannot_transfer_or_be_finalized_again
  NewLang.F0.domain_transfer_preserves_wellFormed
  NewLang.F0.domain_transfer_preserves_identity
  NewLang.F0.domain_transfer_preserves_liveness
  NewLang.F0.domain_transfer_moves_value_carrier
  NewLang.F0.domain_transfer_preserves_other_carriers
  NewLang.F0.domain_transfer_preserves_roots
  NewLang.F0.domain_transfer_preserves_governing_relations
  NewLang.F0.domain_transfer_preserves_packages
  NewLang.F0.domain_transfer_preserves_histories
  NewLang.F0.domain_transfer_preserves_liveFacts
  NewLang.F0.domain_transfer_preserves_survivors
  NewLang.F0.domain_transfer_preserves_DomainLive_dependencies
  NewLang.F0.raw_domain_transfer_preserves_wellFormed
  NewLang.F0.domain_transfer_step_of_raw
  NewLang.F0.domain_transfer_preserves_acquire_ref
  NewLang.F0.domain_transfer_rejects_missing_permission
  NewLang.F0.domain_transfer_rejects_dead_domain
  NewLang.F0.domain_transfer_rejects_wrong_carrier
  NewLang.F0.finalize_domain_preserves_wellFormed
  NewLang.F0.finalize_domain_ends_identity
  NewLang.F0.finalize_domain_consumes_value_carrier
  NewLang.F0.finalize_domain_preserves_other_domains
  NewLang.F0.finalize_domain_liveDomains_subset
  NewLang.F0.finalize_domain_preserves_other_carriers
  NewLang.F0.finalize_domain_preserves_occupancy
  NewLang.F0.finalize_domain_preserves_packages
  NewLang.F0.finalize_domain_preserves_histories
  NewLang.F0.finalize_domain_preserves_survivors
  NewLang.F0.finalize_domain_preserves_carrier_coherence
  NewLang.F0.finalize_domain_requires_no_governed_roots
  NewLang.F0.finalize_domain_rejects_live_governed_root
  NewLang.F0.finalize_domain_requires_no_surviving_domain_dependency
  NewLang.F0.finalize_domain_rejects_surviving_domain_dependency
  NewLang.F0.finalize_domain_rejects_dead_domain
  NewLang.F0.finalize_domain_rejects_missing_permission
  NewLang.F0.finalize_domain_rejects_wrong_carrier
  NewLang.F0.finalized_domain_cannot_acquire_ref
  NewLang.F0.initialize_preserves_domain_carriers
  NewLang.F0.take_preserves_domain_carriers
  NewLang.F0.destroy_preserves_domain_carriers
  NewLang.F0.replace_preserves_domain_carriers
  NewLang.F0.store_preserves_domain_carriers
  NewLang.F0.swap_same_preserves_domain_carriers
  NewLang.F0.swap_distinct_preserves_domain_carriers
  NewLang.F0.wellFormed_live_domain_has_value_carrier
  NewLang.F0.wellFormed_domain_carrier_implies_live_domain
  NewLang.F1.parent_increases_depth
  NewLang.F1.structural_root_has_no_parent
  NewLang.F1.structural_nonroot_has_parent
  NewLang.F1.parent_unique
  NewLang.F1.parent_implies_ancestor
  NewLang.F1.ancestor_increases_depth
  NewLang.F1.ancestor_irreflexive
  NewLang.F1.ancestor_transitive
  NewLang.F1.below_transitive
  NewLang.F1.siblings_are_not_ancestors
  NewLang.F1.known_disjoint_siblings_do_not_overlap
  NewLang.F1.ancestor_implies_overlap
  NewLang.F1.same_place_implies_overlap
  NewLang.F1.root_contains_every_place
  NewLang.F1.local_deps_subset_subtree_deps
  NewLang.F1.ancestor_subtree_deps_subset
  NewLang.F1.child_subtree_deps_subset_parent_subtree_deps
  NewLang.F1.subtree_dependency_has_local_owner
  NewLang.F1.disjoint_sibling_dependency_not_owned_by_other_sibling
  NewLang.F1.live_structural_node_has_current_fact
  NewLang.F1.structural_current_fact_is_recorded
  NewLang.F1.distinct_live_nodes_have_distinct_current_fact_ids
  NewLang.F1.live_structural_node_has_incarnation
  NewLang.F1.structural_incarnation_is_recorded
  NewLang.F1.distinct_live_nodes_have_distinct_incarnations
  NewLang.F1.subtree_dependencies_live
  NewLang.F1.erase_occupancy_live_iff
  NewLang.F1.erase_root_fact_matches_f0
  NewLang.F1.erase_root_incarnation_matches_f0
  NewLang.F1.erase_preserves_root_governing_domain
  NewLang.F1.erase_preserves_live_domains
  NewLang.F1.erase_preserves_domain_carriers
  NewLang.F1.erase_preserves_histories
  NewLang.F1.erase_live_fact
  NewLang.F1.erase_structural_value_fact_to_root
  NewLang.F1.erase_dependencies_are_conservative
  NewLang.F1.erase_installed_package_present
  NewLang.F1.installed_owner_is_unique
  NewLang.F1.erase_root_package_exact
  NewLang.F1.erase_local_dependency_obligation
  NewLang.F1.erase_carrier_unique
  NewLang.F1.erase_places_unique
  NewLang.F1.erase_incarnations_unique
  NewLang.F1.erase_packages_present
  NewLang.F1.erase_domains_valid
  NewLang.F1.erase_dependencies_valid
  NewLang.F1.erase_value_facts_recorded
  NewLang.F1.erase_incarnations_recorded
  NewLang.F1.erase_domain_carrier_coherent
  NewLang.F1.f1_wellFormed_erases_to_f0_wellFormed
  NewLang.F1.Counterexample.Structural.simple_pair_is_wellFormed
  NewLang.F1.Counterexample.Structural.simple_pair_erases_to_wellFormed_f0
  NewLang.F1.Counterexample.Structural.nested_structure_is_wellFormed
  NewLang.F1.Counterexample.Structural.pair_overlap_and_disjointness
  NewLang.F1.Counterexample.Structural.nested_ancestor_witness
  NewLang.F1.Counterexample.Structural.local_dependency_is_visible_from_root_subtree
  NewLang.F1.Counterexample.Structural.structural_dependency_is_retained_by_erasure
  NewLang.F1.Counterexample.Structural.child_histories_survive_flat_erasure
  NewLang.F1.Counterexample.Structural.cyclic_structure_is_rejected
  NewLang.F1.Counterexample.Structural.duplicate_parent_is_rejected
  NewLang.F1.Counterexample.Structural.concrete_duplicate_parent_is_rejected
  NewLang.F1.Counterexample.Structural.duplicate_root_child_fact_is_rejected
  NewLang.F1.Counterexample.Structural.duplicate_structural_incarnation_is_rejected
  NewLang.F1.Counterexample.Structural.stale_structural_dependency_is_rejected
  NewLang.F1.Counterexample.Structural.recorded_stale_fact_is_not_live
  NewLang.F1.Counterexample.Structural.broken_erasure_loses_child_dependency_obligation
  NewLang.F1.below_path_decomposition
  NewLang.F1.relative_positions_injective
  NewLang.F1.extract_value_fragment
  NewLang.F1.extract_value_dependencies
  NewLang.F1.carried_dependency_survives_erasure
  NewLang.F1.carried_structured_dependency_is_retained_by_erasure
  NewLang.F1.mem_live_node_support
  NewLang.F1.mem_affectedBy
  NewLang.F1.target_is_affected
  NewLang.F1.ancestor_of_target_is_affected
  NewLang.F1.descendant_of_target_is_affected
  NewLang.F1.known_disjoint_live_node_is_not_affected
  NewLang.F1.refresh_current_fact
  NewLang.F1.refresh_history_monotone
  NewLang.F1.refresh_records_new_facts
  NewLang.F1.fresh_structural_facts_reject_reuse
  NewLang.F1.fresh_structural_facts_reject_aliasing
  NewLang.F1.refreshed_old_fact_not_live
  NewLang.F1.refreshed_current_facts_unique
  NewLang.F1.refreshed_current_facts_recorded
  NewLang.F1.replace_preserves_wellFormed
  NewLang.F1.replace_post_erases_to_wellFormed_f0
  NewLang.F1.replace_preserves_layout
  NewLang.F1.replace_preserves_all_incarnations
  NewLang.F1.replace_preserves_governing_domain
  NewLang.F1.replace_preserves_fixed_support_and_incarnation_history
  NewLang.F1.replace_current_fact_equation
  NewLang.F1.replace_freshens_affected
  NewLang.F1.replace_freshens_target
  NewLang.F1.replace_freshens_ancestors
  NewLang.F1.replace_freshens_descendants
  NewLang.F1.replace_preserves_known_disjoint_current_facts
  NewLang.F1.replace_history_monotone
  NewLang.F1.replace_old_affected_facts_not_live
  NewLang.F1.replace_preserves_disjoint_live_facts
  NewLang.F1.replace_old_value_survives
  NewLang.F1.replace_installs_new_value
  NewLang.F1.replace_preserves_local_fragments_outside_target
  NewLang.F1.replace_rejects_old_result_invalidated_dependency
  NewLang.F1.replace_rejects_incoming_invalidated_dependency
  NewLang.F1.replace_installs_complete_structured_value
  NewLang.F1.replace_consumes_incoming_loose_carrier
  NewLang.F1.replace_preserves_enclosing_root_carrier_for_subobject
  NewLang.F1.replace_root_carrier_becomes_incoming
  NewLang.F1.replace_rejects_other_surviving_invalidated_dependency
  NewLang.F1.store_preserves_wellFormed
  NewLang.F1.store_post_erases_to_wellFormed_f0
  NewLang.F1.store_preserves_all_incarnations
  NewLang.F1.store_preserves_layout_and_governing_domain
  NewLang.F1.store_requires_target_discardable
  NewLang.F1.store_rejects_nondiscardable_target
  NewLang.F1.store_same_structural_change_set_as_replace
  NewLang.F1.store_current_fact_equation
  NewLang.F1.store_freshens_affected
  NewLang.F1.store_history_monotone
  NewLang.F1.store_preserves_capability_and_incarnation_history
  NewLang.F1.store_old_value_does_not_survive_as_result
  NewLang.F1.store_old_root_carrier_does_not_survive
  NewLang.F1.store_installs_new_value
  NewLang.F1.store_preserves_local_fragments_outside_target
  NewLang.F1.store_preserves_known_disjoint_state
  NewLang.F1.store_old_affected_facts_not_live
  NewLang.F1.store_rejects_other_surviving_invalidated_dependency
  NewLang.F1.store_rejects_incoming_invalidated_dependency
  NewLang.F1.store_preserves_enclosing_root_carrier_for_subobject
  NewLang.F1.store_root_carrier_becomes_incoming
  NewLang.F1.disjoint_targets_are_distinct
  NewLang.F1.swap_same_is_identity
  NewLang.F1.swap_same_consumes_no_fresh_fact
  NewLang.F1.swap_preserves_wellFormed
  NewLang.F1.swap_post_erases_to_wellFormed_f0
  NewLang.F1.swap_distinct_requires_disjoint_targets
  NewLang.F1.swap_distinct_preserves_all_incarnations
  NewLang.F1.swap_distinct_preserves_layout_and_governing_domains
  NewLang.F1.swap_distinct_preserves_carriers_and_domains
  NewLang.F1.swap_distinct_current_fact_equation
  NewLang.F1.swap_distinct_creates_fresh_current_facts
  NewLang.F1.swap_distinct_history_monotone
  NewLang.F1.swap_distinct_new_fact_ids_are_pairwise_distinct
  NewLang.F1.swap_distinct_preserves_unaffected_current_facts
  NewLang.F1.swap_distinct_old_affected_facts_not_live
  NewLang.F1.swap_distinct_installs_right_value_at_left
  NewLang.F1.disjoint_subtrees_have_no_common_node
  NewLang.F1.swap_right_subtree_is_outside_left
  NewLang.F1.swap_distinct_installs_left_value_at_right
  NewLang.F1.swap_distinct_exchanges_complete_structured_values
  NewLang.F1.swap_preserves_external_disjoint_state
  NewLang.F1.swap_rejects_right_value_old_fact_dependency
  NewLang.F1.swap_rejects_left_value_old_fact_dependency
  NewLang.F1.swap_preserves_local_fragments_outside_targets
  NewLang.F1.swap_rejects_external_surviving_invalidated_dependency
  NewLang.F1.swap_whole_root_carriers_are_exchanged
  NewLang.F1.Counterexample.Transition.leaf_replace_is_legal
  NewLang.F1.Counterexample.Transition.nested_aggregate_replace_is_legal
  NewLang.F1.Counterexample.Transition.whole_root_replace_is_legal
  NewLang.F1.Counterexample.Transition.leaf_replace_freshens_root_left_leaf_and_frames_siblings
  NewLang.F1.Counterexample.Transition.nested_replace_freshens_descendants_and_preserves_right
  NewLang.F1.Counterexample.Transition.whole_root_replace_freshens_all_fixed_nodes
  NewLang.F1.Counterexample.Transition.store_eliminates_old_only_structural_dependency
  NewLang.F1.Counterexample.Transition.nested_store_eliminates_old_only_dependency
  NewLang.F1.Counterexample.Transition.replace_rejects_old_self_structural_dependency
  NewLang.F1.Counterexample.Transition.old_self_dependency_rejects_structural_replace_but_allows_store
  NewLang.F1.Counterexample.Transition.incoming_old_structural_fact_rejects_replace_and_store
  NewLang.F1.Counterexample.Transition.external_survivor_dependency_rejects_store
  NewLang.F1.Counterexample.Transition.nondiscardable_fixed_child_rejects_store
  NewLang.F1.Counterexample.Transition.independent_distinct_fixed_swap_is_legal
  NewLang.F1.Counterexample.Transition.fixed_swap_does_not_require_discardable
  NewLang.F1.Counterexample.Transition.same_place_self_dependency_is_legal
  NewLang.F1.Counterexample.Transition.cyclic_structural_swap_laundering_is_rejected
  NewLang.F1.Counterexample.Transition.whole_root_store_is_legal
  NewLang.F1.Counterexample.Transition.disjoint_dependency_replace_is_legal
  NewLang.F1.Counterexample.Transition.incoming_dependency_partition_is_preserved
  NewLang.F1.Counterexample.Transition.missing_ancestor_invalidation_is_not_replace
  NewLang.F1.Counterexample.Transition.missing_descendant_invalidation_is_not_replace
  NewLang.F1.Counterexample.Transition.incarnation_refresh_is_not_replace
  NewLang.F1.Counterexample.Transition.same_place_swap_cannot_allocate_facts
  NewLang.F1.Counterexample.Transition.ancestor_descendant_swap_is_inapplicable
  NewLang.F1.Counterexample.Transition.previously_used_dead_fact_cannot_be_reallocated
  NewLang.F1.Counterexample.Transition.duplicated_new_structural_fact_is_rejected
  NewLang.F1.Counterexample.Transition.returned_value_must_retain_child_local_dependency
  NewLang.F1.Counterexample.Transition.flattened_incoming_package_loses_child_obligation
  NewLang.F1.Counterexample.Transition.incoming_flattening_is_not_the_original_value
  NewLang.F1.Counterexample.Transition.overinvalidating_sibling_rejects_an_otherwise_legal_replace
  NewLang.F1.Counterexample.Transition.independent_aggregate_sibling_swap_is_legal
  NewLang.F1.Counterexample.Transition.aggregate_swap_exchanges_child_values_without_exchanging_incarnations
  NewLang.F1.Counterexample.Transition.self_dependency_allows_same_swap_but_rejects_distinct_swap
  NewLang.F1.Counterexample.Transition.cyclic_candidate_without_dependency_check_is_malformed
  NewLang.F1.Counterexample.Transition.swap_preserves_external_disjoint_dependency_witness
  NewLang.F1.Counterexample.Transition.third_survivor_rejects_structural_swap
  NewLang.F1.Counterexample.Transition.sibling_swap_freshens_shared_ancestors_once_and_frames_external_sibling
  NewLang.F1.Counterexample.Transition.root_discardability_cannot_authorize_child_store
  NewLang.F1.Counterexample.Transition.ancestor_local_dependency_is_preserved_and_rejects_replace
  NewLang.F1.Counterexample.RootTransition.whole_root_swap_is_legal
  NewLang.F1.Counterexample.RootTransition.whole_root_swap_erasure_observations
  NewLang.F1.Counterexample.Transition.omitting_discardability_can_silently_lose_nondiscardable_value
  NewLang.F1.Conditional.Counterexample.Sum.none_to_some_is_legal
  NewLang.F1.Conditional.Counterexample.Sum.some_to_none_is_legal
  NewLang.F1.Conditional.Counterexample.Sum.some_to_same_variant_is_legal
  NewLang.F1.Conditional.Counterexample.Sum.different_payload_variants_is_legal
  NewLang.F1.Conditional.Counterexample.Sum.independent_whole_replace_is_legal
  NewLang.F1.Conditional.Counterexample.Sum.same_variant_whole_replace_restarts_occurrence
  NewLang.F1.Conditional.Counterexample.Sum.whole_store_eliminates_old_only_occurrence_dependency
  NewLang.F1.Conditional.Counterexample.Sum.whole_replace_rejects_old_only_occurrence_dependency
  NewLang.F1.Conditional.Counterexample.Sum.occurrence_dependency_rejects_replace_but_allows_store
  NewLang.F1.Conditional.Counterexample.Sum.same_place_sum_swap_is_exact_noop
  NewLang.F1.Conditional.Counterexample.Sum.same_place_sum_swap_self_dependency_remains_live
  NewLang.F1.Conditional.Counterexample.Sum.whole_incoming_occurrence_dependency_rejects_replace_and_store
  NewLang.F1.Conditional.Counterexample.Sum.whole_external_occurrence_dependency_rejects_replace_and_store
  NewLang.F1.Conditional.Counterexample.Sum.historically_used_but_dead_occurrence_is_not_fresh
  NewLang.F1.Conditional.Counterexample.Sum.historical_occurrence_reuse_rejected
  NewLang.F1.Conditional.Counterexample.Sum.current_variant_discardability_is_an_unsound_store_guard
  NewLang.F1.Conditional.Counterexample.Sum.independent_distinct_sum_swap_is_legal
  NewLang.F1.Conditional.Counterexample.Sum.nonDiscardable_sum_values_can_swap
  NewLang.F1.Conditional.Counterexample.Sum.cyclic_swap_occurrence_laundering_rejected
  NewLang.F1.Conditional.Counterexample.Sum.self_dependency_allows_same_swap_but_rejects_distinct
  NewLang.F1.Conditional.Counterexample.Sum.left_cross_occurrence_swap_dependency_rejected
  NewLang.F1.Conditional.Counterexample.Sum.right_self_occurrence_swap_dependency_rejected
  NewLang.F1.Conditional.Counterexample.Sum.right_cross_occurrence_swap_dependency_rejected
  NewLang.F1.Conditional.Counterexample.Sum.third_survivor_occurrence_swap_dependency_rejected
  NewLang.F1.Conditional.Counterexample.Sum.cyclic_candidate_passes_all_other_invariants_but_fails_dependencies
  NewLang.F1.Conditional.Counterexample.Sum.payload_only_replace_preserves_occurrence_with_self_dependency
  NewLang.F1.Conditional.Counterexample.Sum.payload_only_store_preserves_occurrence
  NewLang.F1.Conditional.Counterexample.Sum.whole_replace_preserving_old_occurrence_is_broken
  NewLang.F1.Conditional.Counterexample.Sum.same_variant_whole_replace_reusing_old_occurrence_is_broken
  NewLang.F1.Conditional.Counterexample.Sum.payload_only_replacement_allocating_occurrence_is_broken
  NewLang.F1.Conditional.Counterexample.Sum.same_place_swap_allocating_occurrence_is_broken
  NewLang.F1.Conditional.Counterexample.Sum.distinct_swap_preserving_source_occurrences_is_broken
  NewLang.F1.Conditional.Counterexample.Sum.distinct_swap_transferring_occurrence_with_value_is_broken
  NewLang.F1.Conditional.Counterexample.Sum.whole_value_result_preserves_payload_but_not_occurrence
  NewLang.F1.Conditional.Counterexample.Sum.whole_vs_payload_only_occurrence_contrast
  NewLang.F1.Conditional.Counterexample.Sum.omitting_static_sum_discardability_can_silently_lose_value
  NewLang.F1.Conditional.Counterexample.Sum.reused_pair_occurrence_allocation_is_rejected
  NewLang.F1.Conditional.Counterexample.Sum.all_negative_dependency_fixtures_have_wellFormed_pre_states
  NewLang.F1.Conditional.Counterexample.Sum.rewriting_dependencies_to_fresh_occurrences_is_not_raw_swap
  NewLang.F1.Conditional.projectFacts_membership
  NewLang.F1.Conditional.live_ordinary_fact_erases
  NewLang.F1.Conditional.wellFormed_erases_to_currentWellFormed
  NewLang.F1.Conditional.surviving_dependencies_are_live
  NewLang.F1.Conditional.recorded_occurrence_is_not_fresh
  NewLang.F1.Conditional.erasure_retains_ordinary_package_dependencies
  NewLang.F1.Conditional.fresh_allocation_cannot_reuse_occurrence
  NewLang.F1.Conditional.allocation_occurrence_is_fresh
  NewLang.F1.Conditional.whole_preserves_wellFormed
  NewLang.F1.Conditional.whole_target_equation
  NewLang.F1.Conditional.whole_preserves_parent_identity
  NewLang.F1.Conditional.whole_preserves_static_frame
  NewLang.F1.Conditional.whole_other_location_unchanged
  NewLang.F1.Conditional.whole_new_package_installed
  NewLang.F1.Conditional.whole_new_occurrence_equation
  NewLang.F1.Conditional.whole_history_monotone
  NewLang.F1.Conditional.whole_fresh_occurrence_recorded
  NewLang.F1.Conditional.whole_fresh_current_facts_recorded
  NewLang.F1.Conditional.whole_old_occurrence_ended
  NewLang.F1.Conditional.whole_replace_old_package_survives
  NewLang.F1.Conditional.whole_store_old_package_does_not_survive
  NewLang.F1.Conditional.whole_incoming_no_longer_loose
  NewLang.F1.Conditional.whole_store_requires_static_sum_discardability
  NewLang.F1.Conditional.whole_store_rejects_nonDiscardable_sum
  NewLang.F1.Conditional.whole_rejects_ended_occurrence_in_survivor
  NewLang.F1.Conditional.whole_replace_rejects_returned_occurrence_dependency
  NewLang.F1.Conditional.whole_rejects_incoming_occurrence_dependency
  NewLang.F1.Conditional.whole_replace_value_transfers_without_occurrence
  NewLang.F1.Conditional.payload_preserves_wellFormed
  NewLang.F1.Conditional.payload_preserves_occurrence
  NewLang.F1.Conditional.payload_preserves_parent_identity
  NewLang.F1.Conditional.payload_installs_new_value
  NewLang.F1.Conditional.payload_occurrence_dependency_remains_live
  NewLang.F1.Conditional.payload_old_current_fact_dies
  NewLang.F1.Conditional.payload_rejects_surviving_old_value_dependency
  NewLang.F1.Conditional.payload_store_requires_static_payload_discardability
  NewLang.F1.Conditional.swap_preserves_wellFormed
  NewLang.F1.Conditional.swap_same_is_identity
  NewLang.F1.Conditional.swap_same_preserves_variant_occurrence_history
  NewLang.F1.Conditional.swap_distinct_target_equations
  NewLang.F1.Conditional.swap_distinct_preserves_parent_identities
  NewLang.F1.Conditional.swap_distinct_exchanges_values_without_rewriting_dependencies
  NewLang.F1.Conditional.swap_distinct_preserves_frame
  NewLang.F1.Conditional.swap_distinct_other_location_unchanged
  NewLang.F1.Conditional.swap_distinct_both_packages_survive
  NewLang.F1.Conditional.swap_distinct_fresh_occurrences_and_history
  NewLang.F1.Conditional.swap_distinct_old_left_occurrence_ended
  NewLang.F1.Conditional.swap_distinct_old_right_occurrence_ended
  NewLang.F1.Conditional.swap_rejects_any_surviving_ended_occurrence
  NewLang.F1.Conditional.swap_rejects_left_package_occurrence_dependency
  NewLang.F1.Conditional.swap_rejects_right_package_occurrence_dependency
  NewLang.F1.Conditional.whole_old_root_value_fact_ended
  NewLang.F1.Conditional.whole_preserves_erased_fixed_identity
  NewLang.F1.Conditional.whole_store_requires_all_possible_payload_types_discardable
  NewLang.F1.Conditional.payload_fresh_facts_and_history
  NewLang.F1.Conditional.payload_store_rejects_nonDiscardable_payload
  NewLang.F1.Conditional.swap_distinct_two_current_facts_fresh_distinct_recorded
  NewLang.F1.Conditional.live_occurrence_has_live_enclosing_root_and_domain
  NewLang.F1.Conditional.conditional_payload_is_not_added_to_fixed_incarnation_support
  NewLang.F1.Conditional.whole_new_occurrence_differs_from_old
  NewLang.F1.Conditional.whole_payloadless_incoming_has_no_occurrence
  NewLang.F1.Backing.Counterexample.Boundary.every_conditional_wellFormed_state_has_backing
  NewLang.F1.Backing.Counterexample.Boundary.independent_whole_replace_has_backing
  NewLang.F1.Backing.Counterexample.Boundary.old_only_dependency_store_has_backing
  NewLang.F1.Backing.Counterexample.Boundary.independent_distinct_swap_has_backing
  NewLang.F1.Backing.Counterexample.Boundary.same_sum_swap_with_backing_is_exact_noop
  NewLang.F1.Backing.Counterexample.Boundary.distinct_placement_is_not_exchanged
  NewLang.F1.Backing.Counterexample.Boundary.broken_package_placement_exchange_breaks_frame
  NewLang.F1.Backing.Counterexample.Boundary.broken_package_placement_exchange_is_geometrically_valid
  NewLang.F1.Backing.Counterexample.Boundary.readwrite_initialize_is_legal
  NewLang.F1.Backing.Counterexample.Boundary.writeonly_initialize_is_legal
  NewLang.F1.Backing.Counterexample.Boundary.readwrite_take_is_legal
  NewLang.F1.Backing.Counterexample.Boundary.writeonly_destroy_is_legal
  NewLang.F1.Backing.Counterexample.Boundary.writeonly_take_is_rejected
  NewLang.F1.Backing.Counterexample.Boundary.readonly_initialize_is_rejected
  NewLang.F1.Backing.Counterexample.Boundary.broken_destroy_read_guard_rejects_valid_language_case
  NewLang.F1.Backing.Counterexample.Boundary.same_placement_restart_is_legal_but_old_ptr_is_stale
  NewLang.F1.Backing.Counterexample.Boundary.readonly_control_isolates_write_applicability
  NewLang.F1.Backing.Counterexample.Boundary.writeonly_take_control_isolates_read_applicability
  NewLang.F1.Backing.Counterexample.Boundary.stronger_ptr_evidence_is_rejected
  NewLang.F1.Backing.Counterexample.Boundary.dead_backing_control_isolates_region_liveness
  NewLang.F1.Backing.Counterexample.Boundary.equal_hypothetical_addresses_do_not_identify_regions
  NewLang.F1.Backing.Counterexample.Boundary.value_transfer_installs_at_destination_not_source
  NewLang.F1.Backing.Counterexample.Boundary.broken_value_owned_source_placement_is_rejected
  NewLang.F1.Backing.Counterexample.Boundary.swap_rejects_package_owned_placement_exchange
  NewLang.F1.Backing.Counterexample.Boundary.broken_swap_control_keeps_semantics_and_geometry_valid
  NewLang.F1.Backing.whole_preserves_placement
  NewLang.F1.Backing.whole_replace_preserves_target_placement
  NewLang.F1.Backing.whole_store_preserves_target_placement
  NewLang.F1.Backing.whole_lift_is_legal
  NewLang.F1.Backing.payload_preserves_placement
  NewLang.F1.Backing.payload_backing_wellFormed
  NewLang.F1.Backing.swap_same_is_identity
  NewLang.F1.Backing.swap_preserves_placement_and_backing
  NewLang.F1.Backing.swap_lift_is_legal
  NewLang.F1.Backing.swap_distinct_exchanges_values_not_placement
  NewLang.F1.Backing.whole_step_erases
  NewLang.F1.Backing.swap_step_erases
  NewLang.F1.Backing.payload_lift_is_legal
  NewLang.F1.Backing.payload_step_erases
  NewLang.F1.Backing.initialize_requires_destination_write
  NewLang.F1.Backing.initialize_rejects_readonly_region
  NewLang.F1.Backing.initialize_rejects_readonly_evidence
  NewLang.F1.Backing.initialize_uses_destination_placement
  NewLang.F1.Backing.initialize_preserves_other_placements
  NewLang.F1.Backing.initialize_produces_current_ptr
  NewLang.F1.Backing.initialize_ptr_access_nonamplification
  NewLang.F1.Backing.initialize_value_transfer_does_not_transfer_placement
  NewLang.F1.Backing.initialize_reused_placement_does_not_revive_old_ptr
  NewLang.F1.Backing.take_requires_source_read
  NewLang.F1.Backing.take_rejects_writeonly_ptr
  NewLang.F1.Backing.take_rejects_writeonly_region
  NewLang.F1.Backing.take_ends_placement_not_backing
  NewLang.F1.Backing.destroy_ends_placement_not_backing
  NewLang.F1.Backing.take_live_region_remains_live
  NewLang.F1.Backing.destroy_live_region_remains_live
  NewLang.F1.Backing.take_transfers_value_without_source_placement
  NewLang.F1.Backing.destroy_requires_discardable
  NewLang.F1.Backing.take_then_restart_rejects_old_ptr
  NewLang.F1.Backing.destroy_then_restart_rejects_old_ptr
  NewLang.F1.Backing.initialize_step_erases
  NewLang.F1.Backing.take_step_erases
  NewLang.F1.Backing.destroy_step_erases
  NewLang.F1.Backing.accessLe_refl
  NewLang.F1.Backing.accessLe_trans
  NewLang.F1.Backing.evidence_cannot_amplify_read
  NewLang.F1.Backing.evidence_cannot_amplify_write
  NewLang.F1.Backing.sum_wellFormed_erases_to_conditional
  NewLang.F1.Backing.sum_wellFormed_erases_to_current
  NewLang.F1.Backing.sum_wellFormed_erases_to_f0
  NewLang.F1.Backing.flat_wellFormed_erases_to_f0
  NewLang.F1.Backing.live_root_requires_live_region
  NewLang.F1.Backing.dead_region_cannot_back_live_root
  NewLang.F1.Occupancy.consumeOne_active_iff
  NewLang.F1.Occupancy.consumeOne_consumes_source
  NewLang.F1.Occupancy.consumeOne_produces_result
  NewLang.F1.Occupancy.consumeOne_conserves_footprint
  NewLang.F1.Occupancy.split_consumes_source_and_produces_two
  NewLang.F1.Occupancy.split_preserves_identity_nonempty_partition
  NewLang.F1.Occupancy.split_rejects_left_endpoint
  NewLang.F1.Occupancy.split_rejects_right_endpoint
  NewLang.F1.Occupancy.split_conserves_all_byte_responsibility
  NewLang.F1.Occupancy.split_preserves_scope
  NewLang.F1.Occupancy.merge_consumes_both_inputs
  NewLang.F1.Occupancy.merge_preserves_identity_and_exact_union
  NewLang.F1.Occupancy.merge_rejects_different_regions
  NewLang.F1.Occupancy.merge_rejects_nonadjacent
  NewLang.F1.Occupancy.merge_conserves_all_byte_responsibility
  NewLang.F1.Occupancy.into_slot_consumes_raw_exact_range
  NewLang.F1.Occupancy.into_slot_rejects_larger_range
  NewLang.F1.Occupancy.into_slot_conserves_all_byte_responsibility
  NewLang.F1.Occupancy.erase_slot_consumes_empty_exact_range
  NewLang.F1.Occupancy.erase_slot_conserves_all_byte_responsibility
  NewLang.F1.Occupancy.erase_slot_has_no_access_precondition
  NewLang.F1.Occupancy.empty_conversion_preserves_accounting
  NewLang.F1.Occupancy.into_slot_step_of_raw
  NewLang.F1.Occupancy.erase_slot_step_of_raw
  NewLang.F1.Occupancy.erase_slot_is_total
  NewLang.F1.Occupancy.empty_claim_conversion_preserves_flat
  NewLang.F1.Occupancy.empty_claim_conversion_preserves_sum
  NewLang.F1.Occupancy.Counterexample.endpoint_split_controls
  NewLang.F1.Occupancy.Counterexample.gap_split_isolates_lost_responsibility
  NewLang.F1.Occupancy.Counterexample.overlapping_split_isolates_duplication
  NewLang.F1.Occupancy.Counterexample.merge_gap_and_overlap_controls
  NewLang.F1.Occupancy.Counterexample.different_region_merge_isolates_identity
  NewLang.F1.Occupancy.Counterexample.different_region_merge_control
  NewLang.F1.Occupancy.Counterexample.larger_into_slot_tail_control
  NewLang.F1.Occupancy.Counterexample.unchecked_into_slot_loses_tail
  NewLang.F1.Occupancy.Counterexample.split_merge_roundtrip_is_legal
  NewLang.F1.Occupancy.Counterexample.single_raw_accounting
  NewLang.F1.Occupancy.Counterexample.raw_state_wellFormed
  NewLang.F1.Occupancy.Counterexample.split_is_legal
  NewLang.F1.Occupancy.Counterexample.slot_state_wellFormed
  NewLang.F1.Occupancy.Counterexample.into_slot_is_legal
  NewLang.F1.Occupancy.Counterexample.first_wellFormed
  NewLang.F1.Occupancy.Counterexample.taken_wellFormed
  NewLang.F1.Occupancy.Counterexample.restart_wellFormed
  NewLang.F1.Occupancy.Counterexample.ended_wellFormed
  NewLang.F1.Occupancy.Counterexample.initialize_is_legal
  NewLang.F1.Occupancy.Counterexample.take_is_legal
  NewLang.F1.Occupancy.Counterexample.same_range_restart_is_legal_and_old_ptr_stays_stale
  NewLang.F1.Occupancy.Counterexample.destroy_is_legal
  NewLang.F1.Occupancy.Counterexample.erase_slot_is_legal
  NewLang.F1.Occupancy.Counterexample.merged_wellFormed
  NewLang.F1.Occupancy.Counterexample.merge_after_lifecycle_is_legal
  NewLang.F1.Occupancy.Counterexample.writeonly_destroy_is_legal
  NewLang.F1.Occupancy.Counterexample.writeonly_take_rejected_but_destroy_allowed
  NewLang.F1.Occupancy.Counterexample.complete_responsibility_cycle
  NewLang.F1.Occupancy.Counterexample.live_iff
  NewLang.F1.Occupancy.Counterexample.semantic_wf
  NewLang.F1.Occupancy.Counterexample.pair_shape
  NewLang.F1.Occupancy.Counterexample.pair_accounting
  NewLang.F1.Occupancy.Counterexample.initialize_wrong_range_control_has_valid_endpoints
  NewLang.F1.Occupancy.Counterexample.take_wrong_slot_control_has_valid_endpoints
  NewLang.F1.Occupancy.Counterexample.erase_slot_wrong_range_control_has_valid_endpoints
  NewLang.F1.Occupancy.Counterexample.destroy_lost_responsibility_control
  NewLang.F1.Occupancy.Counterexample.erase_slot_larger_or_different_region_controls
  NewLang.F1.Occupancy.Counterexample.representation_change_is_possible_without_new_authority
  NewLang.F1.Occupancy.Counterexample.storage_and_slot_overlap_isolated
  NewLang.F1.Occupancy.Counterexample.slot_and_live_root_overlap_isolated
  NewLang.F1.Occupancy.Counterexample.outstanding_slot_blocks_full_storage
  NewLang.F1.Occupancy.Counterexample.outstanding_root_blocks_full_storage
  NewLang.F1.Occupancy.initialize_consumes_slot_and_preserves_exact_responsibility
  NewLang.F1.Occupancy.initialize_conserves_byte_responsibility
  NewLang.F1.Occupancy.initialize_preserves_backing_lifetime_and_scope
  NewLang.F1.Occupancy.initialize_requires_reviewed_write_access
  NewLang.F1.Occupancy.initialize_rejects_readonly_backing
  NewLang.F1.Occupancy.initialize_step_erases_to_backing
  NewLang.F1.Occupancy.take_consumes_root_and_returns_same_slot
  NewLang.F1.Occupancy.destroy_consumes_root_and_returns_same_slot
  NewLang.F1.Occupancy.take_conserves_byte_responsibility
  NewLang.F1.Occupancy.destroy_conserves_byte_responsibility
  NewLang.F1.Occupancy.take_does_not_end_backing
  NewLang.F1.Occupancy.destroy_does_not_end_backing
  NewLang.F1.Occupancy.take_transfers_value_without_placement
  NewLang.F1.Occupancy.take_requires_reviewed_read_access
  NewLang.F1.Occupancy.take_rejects_writeonly_ptr
  NewLang.F1.Occupancy.take_step_erases_to_backing
  NewLang.F1.Occupancy.destroy_step_erases_to_backing
  NewLang.F1.Occupancy.take_then_same_range_restart_rejects_stale_ptr
  NewLang.F1.Occupancy.representation_mutation_cannot_mint_authority
  NewLang.F1.Occupancy.accounting_derives_physical_wellFormed
  NewLang.F1.Occupancy.wellFormed_erases_to_backing
  NewLang.F1.Occupancy.wellFormed_erases_to_f0
  NewLang.F1.Occupancy.sum_wellFormed_erases_to_backing
  NewLang.F1.Occupancy.sum_wellFormed_erases_to_conditional
  NewLang.F1.Occupancy.sum_wellFormed_erases_to_current
  NewLang.F1.Occupancy.sum_wellFormed_erases_to_f0
  NewLang.F1.Occupancy.surviving_claim_requires_live_backing
  NewLang.F1.Occupancy.every_scoped_byte_has_unique_responsibility
  NewLang.F1.Occupancy.nonempty_claim_cannot_be_covered_twice
  NewLang.F1.Occupancy.full_region_storage_excludes_outstanding_subclaim
  NewLang.F1.Occupancy.storage_is_affine_nonDiscardable
  NewLang.F1.Occupancy.slot_is_empty_authority_not_live_value
  NewLang.F1.Occupancy.split_preserves_no_overlap
  NewLang.F1.Occupancy.merge_preserves_no_overlap
  NewLang.F1.Occupancy.range_membership
  NewLang.F1.Occupancy.nonempty_range_has_position
  NewLang.F1.Occupancy.split_ranges_are_nonempty
  NewLang.F1.Occupancy.split_ranges_exact_union
  NewLang.F1.Occupancy.split_ranges_disjoint
  NewLang.F1.Occupancy.split_extents_preserve_region
  NewLang.F1.Occupancy.split_extents_exact_union
  NewLang.F1.Occupancy.split_extents_disjoint
  NewLang.F1.Occupancy.adjacent_ranges_disjoint
  NewLang.F1.Occupancy.adjacent_ranges_exact_union
  NewLang.F1.Occupancy.adjacent_extents_exact_union
  NewLang.F1.Occupancy.adjacent_extents_disjoint
  NewLang.F1.Occupancy.split_merge_range_roundtrip
  NewLang.F1.Occupancy.extent_footprint_nonempty
  NewLang.F1.Occupancy.fitting_extent_is_inside_backing
  NewLang.F1.Relocation.three_way_partition
  NewLang.F1.Relocation.RawMove.source_and_inputs_consumed
  NewLang.F1.Relocation.RawMove.root_and_raw_outputs_produced
  NewLang.F1.Relocation.RawMove.occupancy_conserved
  NewLang.F1.Relocation.RawMove.intersection_never_returned_as_raw
  NewLang.F1.Relocation.Counterexample.stage_accounting
  NewLang.F1.Relocation.Counterexample.independent_before_wellFormed
  NewLang.F1.Relocation.Counterexample.independent_after_wellFormed
  NewLang.F1.Relocation.Counterexample.half_endpoints_wellFormed
  NewLang.F1.Relocation.Counterexample.public_half_transition_rejected
  NewLang.F1.Relocation.Counterexample.lost_semantic_package_rejected
  NewLang.F1.Relocation.Counterexample.reused_root_incarnation_rejected
  NewLang.F1.Relocation.Counterexample.reused_source_current_fact_rejected
  NewLang.F1.Relocation.Counterexample.reused_payload_occurrence_rejected
  NewLang.F1.Relocation.Counterexample.retired_occurrence_not_fresh
  NewLang.F1.Relocation.Counterexample.transferred_source_placement_control
  NewLang.F1.Relocation.Counterexample.copied_governing_relation_rejected
  NewLang.F1.Relocation.Counterexample.retargeted_old_ptr_receipt_rejected
  NewLang.F1.Relocation.Counterexample.duplicated_package_breaks_only_carrier_rule
  NewLang.F1.Relocation.Counterexample.implicit_embedded_ptr_fixup_rejected
  NewLang.F1.Relocation.Counterexample.same_extent_end_restart_rejected
  NewLang.F1.Relocation.Counterexample.hypothetical_address_coincidence_does_not_equate_regions
  NewLang.F1.Relocation.Counterexample.singleton_invariant
  NewLang.F1.Relocation.Counterexample.before_invariant
  NewLang.F1.Relocation.Counterexample.after_invariant
  NewLang.F1.Relocation.Counterexample.independent_dependencies
  NewLang.F1.Relocation.Counterexample.overlap_intersection_raw_duplication_rejected
  NewLang.F1.Relocation.Counterexample.destination_raw_not_consumed_rejected
  NewLang.F1.Relocation.Counterexample.source_difference_responsibility_lost_rejected
  NewLang.F1.Relocation.Counterexample.raw_move
  NewLang.F1.Relocation.Counterexample.independent_move_is_legal
  NewLang.F1.Relocation.Counterexample.disjoint_relocation_is_legal
  NewLang.F1.Relocation.Counterexample.overlapping_relocation_is_legal
  NewLang.F1.Relocation.Counterexample.different_region_relocation_is_legal
  NewLang.F1.Relocation.Counterexample.partial_overlap_three_responsibilities
  NewLang.F1.Relocation.Counterexample.package_with_embedded_ptr_and_owned_storage_transfers_once
  NewLang.F1.Relocation.Counterexample.before_occurrence_dependencies_valid
  NewLang.F1.Relocation.Counterexample.before_occurrence_wellFormed
  NewLang.F1.Relocation.Counterexample.same_place_requires_no_ending_or_read_write
  NewLang.F1.Relocation.Counterexample.source_occurrence_dependency_rejects_move
  NewLang.F1.Relocation.Counterexample.external_occurrence_dependency_rejects_move
  NewLang.F1.Relocation.wellFormed_erases_to_accounting
  NewLang.F1.Relocation.wellFormed_erases_to_backing
  NewLang.F1.Relocation.wellFormed_erases_to_conditional
  NewLang.F1.Relocation.wellFormed_erases_to_current
  NewLang.F1.Relocation.wellFormed_erases_to_f0
  NewLang.F1.Relocation.same_place_is_exact_identity
  NewLang.F1.Relocation.same_place_is_legal
  NewLang.F1.Relocation.same_place_preserves_token_and_accounting
  NewLang.F1.Relocation.current_token_erases_to_f0
  NewLang.F1.Relocation.RawMove.live_after
  NewLang.F1.Relocation.RawMove.source_ended_destination_started
  NewLang.F1.Relocation.RawMove.destination_root
  NewLang.F1.Relocation.RawMove.other_root
  NewLang.F1.Relocation.RawMove.package_and_authority_data_unchanged
  NewLang.F1.Relocation.RawMove.same_domain_fresh_relation
  NewLang.F1.Relocation.RawMove.destination_does_not_inherit_place
  NewLang.F1.Relocation.RawMove.fresh_incarnation_and_history
  NewLang.F1.Relocation.RawMove.fresh_current_and_occurrence_history
  NewLang.F1.Relocation.RawMove.allocations_recorded
  NewLang.F1.Relocation.RawMove.erased_fixed_root_is_fresh
  NewLang.F1.Relocation.RawMove.old_root_fact_not_live
  NewLang.F1.Relocation.RawMove.old_occurrence_not_live
  NewLang.F1.Relocation.RawMove.old_payload_fact_not_live
  NewLang.F1.Relocation.RawMove.all_survivors_retained
  NewLang.F1.Relocation.RawMove.package_installed_once
  NewLang.F1.Relocation.RawMove.old_token_stale
  NewLang.F1.Relocation.RawMove.old_incarnation_cannot_revive
  NewLang.F1.Relocation.RawMove.fresh_destination_token
  NewLang.F1.Relocation.RawMove.exact_placement_and_backing
  NewLang.F1.Relocation.RawMove.fresh_receipt_not_copied
  NewLang.F1.Relocation.RawMove.embedded_ptrs_and_owned_claims_not_fixed_up
  NewLang.F1.Relocation.RawMove.retired_incarnation_stays_unallocatable
  NewLang.F1.Relocation.step_preserves_wellFormed
  NewLang.F1.Relocation.step_has_unique_byte_responsibility
  NewLang.F1.Relocation.move_rejects_surviving_old_occurrence_dependency
  NewLang.F1.Relocation.no_recoverable_half_state
  NewLang.F2.May.join_left
  NewLang.F2.May.join_right
  NewLang.F2.May.unknown_contains
  NewLang.F2.represents_widen
  NewLang.F2.represented_safety
  NewLang.F2.widening_never_erases_blocker
  NewLang.F2.lost_correlation_cannot_justify_invalidation
  NewLang.F2.unknown_is_not_dependency_free
  NewLang.F2.Counterexample.same_type_does_not_mean_same_package
  NewLang.F2.Counterexample.duplicated_affine_responsibility_rejected
  NewLang.F2.Counterexample.lost_affine_responsibility_rejected
  NewLang.F2.Counterexample.outer_availability_cannot_be_widened
  NewLang.F2.Counterexample.iteration_local_dependency_cannot_escape
  NewLang.F2.Counterexample.fork_identity_cannot_collapse_to_type
  NewLang.F2.Counterexample.origin_singleton_loses_fork_alternative
  NewLang.F2.Counterexample.copy_mutation_does_not_clear_hidden_affine_blocker
  NewLang.F2.Counterexample.pure_copy_cyclic_sound
  NewLang.F2.Counterexample.unchanged_continue
  NewLang.F2.Counterexample.unchanged_postFixpoint
  NewLang.F2.Counterexample.unchanged_symbolic_affine_carry
  NewLang.F2.Counterexample.hidden_dependency_recurs_without_erasure
  NewLang.F2.Counterexample.transformed_affine_carry
  NewLang.F2.Counterexample.two_edges_distinct_alternatives
  NewLang.F2.Counterexample.all_continue_sequences_exact_availability
  NewLang.F2.Counterexample.first_entry_only_is_not_inductive
  NewLang.F2.Counterexample.underapproximation_is_not_sound
  NewLang.F2.Counterexample.omitted_continue_edge_breaks_closure
  NewLang.F2.Counterexample.larger_header_is_inductive
  NewLang.F2.Counterexample.larger_than_reachable_is_still_sound
  NewLang.F2.Counterexample.dropped_join_blocker_looks_safe_but_conflicts
  NewLang.F2.Counterexample.unknown_retains_concrete_blocker
  NewLang.F2.Counterexample.every_finite_edge_sequence_has_trace
  NewLang.F2.Counterexample.every_finite_edge_sequence_is_sound
  NewLang.F2.Counterexample.exit_wellFormed
  NewLang.F2.Counterexample.exit_dependencies_live
  NewLang.F2.Counterexample.exits_postFixpoint
  NewLang.F2.Counterexample.exit_represented
  NewLang.F2.Counterexample.finite_break_bound
  NewLang.F2.Counterexample.concrete_break
  NewLang.F2.Counterexample.finite_copy_break_alternatives
  NewLang.F2.Counterexample.finite_noncopy_break_alternatives
  NewLang.F2.Counterexample.break_does_not_feed_header
  NewLang.F2.Counterexample.zero_break_edge_set
  NewLang.F2.Counterexample.zero_break_postFixpoint
  NewLang.F2.Counterexample.zero_break_still_has_continue
  NewLang.F2.Counterexample.concrete_return
  NewLang.F2.Counterexample.return_does_not_feed_header
  NewLang.F2.Counterexample.return_is_not_a_break_result
  NewLang.F2.Counterexample.zero_break_cannot_synthesize_unit_like_result
  NewLang.F2.Counterexample.finite_indexed_break_bound
  NewLang.F2.Counterexample.finite_indexed_join
  NewLang.F2.Counterexample.finite_exit_analysis_after_inductive_header
  NewLang.F2.Counterexample.next_binding_unused
  NewLang.F2.Counterexample.next_package_unused
  NewLang.F2.Counterexample.next_fact_unused
  NewLang.F2.Counterexample.entry_wellFormed
  NewLang.F2.Counterexample.advance_dependencies
  NewLang.F2.Counterexample.advance_wellFormed
  NewLang.F2.Counterexample.advance_frame
  NewLang.F2.Counterexample.unchanged_wellFormed
  NewLang.F2.Counterexample.unchanged_frame
  NewLang.F2.Counterexample.entry_represented
  NewLang.F2.Counterexample.advanced_represented
  NewLang.F2.Counterexample.cyclic_continue
  NewLang.F2.Counterexample.cyclic_postFixpoint
  NewLang.F2.break_edges_finite
  NewLang.F2.break_is_normal_exit
  NewLang.F2.continue_excludes_break_return
  NewLang.F2.break_excludes_header
  NewLang.F2.return_excludes_header_and_break
  NewLang.F2.zero_break_has_no_normal_result
  NewLang.F2.reachable_break_summary_sound
  NewLang.F2.break_types_availability_agree
  NewLang.F2.break_runtime_affine_unique
  NewLang.F2.exit_representation_monotone
  NewLang.F2.finite_break_join_sound
  NewLang.F2.entry_reachable
  NewLang.F2.continue_preserves_reachability
  NewLang.F2.trace_preserves_representation
  NewLang.F2.arbitrary_finite_continue_sound
  NewLang.F2.post_fixpoint_sound
  NewLang.F2.trace_implies_reachable
  NewLang.F2.trace_append_step
  NewLang.F2.reachable_has_finite_trace
  NewLang.F2.any_inductive_overapproximation_suffices
  NewLang.F2.header_count_and_slot_correspondence
  NewLang.F2.represented_exact_layer
  NewLang.F2.Continue.next_binding_fresh
  NewLang.F2.Continue.outer_availability_exact
  NewLang.F2.Continue.no_iteration_dependency_escape
  NewLang.F2.Continue.affine_slot_unique
  NewLang.F2.Continue.unchanged_transfer_exactly_once
  NewLang.F2.Continue.transformed_identity_distinct
  NewLang.F2.Continue.transformed_transfer_exactly_once
  NewLang.F2.Continue.histories_monotone
  NewLang.F2.Continue.mutated_current_fact_is_not_live
  NewLang.F3.Memory.SumLifetime.coarse_live
  NewLang.F3.Memory.SumLifetime.coarse_survives
  NewLang.F3.Memory.SumLifetime.coarse_live_facts
  NewLang.F3.Memory.SumLifetime.coarse_wellFormed
  NewLang.F3.Memory.SumLifetime.remaining_was_surviving
  NewLang.F3.Memory.SumLifetime.live_not_ended_remains_live
  NewLang.F3.Memory.SumLifetime.end_semantic_invariant
  NewLang.F3.Memory.SumLifetime.end_semantic_wellFormed
  NewLang.F3.Memory.SumLifetime.end_all_facts_dead
  NewLang.F3.Memory.SumLifetime.end_placement_empty
  NewLang.F3.Memory.SumLifetime.end_accounting
  NewLang.F3.Memory.SumLifetime.end_candidate_wellFormed
  NewLang.F3.Memory.SumLifetime.take_preserves_wellFormed
  NewLang.F3.Memory.SumLifetime.destroy_preserves_wellFormed
  NewLang.F3.Memory.SumLifetime.end_preserves_value_and_history
  NewLang.F3.Memory.SumLifetime.take_returns_unique_loose
  NewLang.F3.Memory.SumLifetime.destroy_old_package_not_surviving
  NewLang.F3.Memory.SumLifetime.end_responsibility
  NewLang.F3.Memory.SumLifetime.end_footprint_conserved
  NewLang.F3.Memory.SumLifetime.take_rejects_ended_dependency
  NewLang.F3.Memory.SumLifetime.destroy_rejects_external_ended_dependency
  NewLang.F3.Memory.SumLifetime.end_rejects_stale_root_token
  NewLang.F3.Memory.SumLifetime.take_requires_read_and_ending
  NewLang.F3.Memory.SumLifetime.destroy_requires_discard_and_ending
  NewLang.F3.Memory.SumLifetime.raw_take_returns_exact_slot
  NewLang.F3.Memory.SumLifetime.raw_destroy_returns_exact_slot
  NewLang.F3.Memory.SumLifetime.end_frames_other_locations
  NewLang.F3.Memory.SumLifetime.coarse_take_candidate
  NewLang.F3.Memory.SumLifetime.coarse_destroy_candidate
  NewLang.F3.Memory.SumLifetime.coarse_state_wellFormed
  NewLang.F3.Memory.SumLifetime.raw_take_projects
  NewLang.F3.Memory.SumLifetime.raw_destroy_projects
  NewLang.F3.Memory.SumLifetime.rich_take_projects_to_legal_coarse
  NewLang.F3.Memory.SumLifetime.rich_destroy_projects_to_legal_coarse
  NewLang.F3.Memory.SumLifetime.rich_take_reviewed_erasure_wellFormed
  NewLang.F3.Memory.SumLifetime.rich_destroy_reviewed_erasure_wellFormed
  NewLang.F3.Memory.SumLifetime.Counterexample.independent_rich_take_is_legal
  NewLang.F3.Memory.SumLifetime.Counterexample.take_positive_endpoint_and_exact_responsibility
  NewLang.F3.Memory.SumLifetime.Counterexample.occurrence_payload_root_facts_end
  NewLang.F3.Memory.SumLifetime.Counterexample.dependency_data_and_retired_history_preserved
  NewLang.F3.Memory.SumLifetime.Counterexample.external_and_fixed_domain_dependency_remain_valid
  NewLang.F3.Memory.SumLifetime.Counterexample.returned_occurrence_dependency_rejects_take
  NewLang.F3.Memory.SumLifetime.Counterexample.returned_payload_dependency_rejects_take
  NewLang.F3.Memory.SumLifetime.Counterexample.returned_root_fact_dependency_rejects_take
  NewLang.F3.Memory.SumLifetime.Counterexample.destroy_can_consume_old_only_occurrence_dependency
  NewLang.F3.Memory.SumLifetime.Counterexample.old_occurrence_dependency_rejects_take_but_allows_destroy
  NewLang.F3.Memory.SumLifetime.Counterexample.external_occurrence_dependency_rejects_take_and_destroy
  NewLang.F3.Memory.SumLifetime.Counterexample.coarse_legal_take_does_not_imply_rich_legal_take
  NewLang.F3.Memory.SumLifetime.Counterexample.raw_candidate_has_structure_and_accounting_but_bad_dependencies
  NewLang.F3.Memory.SumLifetime.Counterexample.stale_root_token_rejected_after_both_endings
  NewLang.F3.Memory.SumLifetime.Counterexample.take_rejects_missing_read_or_ending
  NewLang.F3.Memory.SumLifetime.Counterexample.destroy_rejects_missing_discard_or_ending
  NewLang.F3.Memory.SumLifetime.Counterexample.wrong_region_extent_conversion_rejected
  NewLang.F3.Memory.SumLifetime.Counterexample.missing_responsibility_rejected
  NewLang.F3.Memory.SumLifetime.Counterexample.duplicated_responsibility_rejected
  NewLang.F0.StableRoot.replace_preserves_preexisting_ptr_target
  NewLang.F0.StableRoot.replace_preserves_preexisting_ptr_acquisition
  NewLang.F0.StableRoot.replace_then_take_rejects_preexisting_ptr
  NewLang.F0.StableRoot.replace_then_destroy_rejects_preexisting_ptr
  NewLang.F0.Counterexample.Reference.stable_root_replace_then_take_contrast
  NewLang.F0.Counterexample.Reference.stable_root_replace_then_destroy_contrast
  NewLang.F0.Counterexample.Reference.stable_root_replace_still_requires_acquisition_guards
  NewLang.F1.FixedChange.field_replace_preserves_target_and_root_identity
  NewLang.F1.FixedChange.field_replace_preserves_target_incarnation_liveness
  NewLang.F1.FixedChange.field_replace_frames_known_disjoint_value
  NewLang.F1.FixedChange.field_replace_refreshes_ancestor_and_ends_old_fact
  NewLang.F1.FixedChange.field_replace_rejects_returned_target_dependency
  NewLang.F1.FixedChange.field_replace_rejects_surviving_overlapping_dependency
  NewLang.F1.FixedChange.field_replace_dependency_superset_keeps_blocker
  NewLang.F1.FixedChange.field_replace_allows_enclosing_root_ptr_acquisition
  NewLang.F1.FixedChange.erased_field_incarnation_cannot_acquire_as_root
  NewLang.F1.Counterexample.Transition.field_change_preserves_parent_identity_and_refreshes_ancestor
  NewLang.F1.Counterexample.Transition.sibling_value_and_dependency_survive_field_change
  NewLang.F1.Counterexample.Transition.surviving_parent_value_dependency_blocks_field_change
  NewLang.F1.Counterexample.Transition.larger_finite_dependency_set_keeps_parent_blocker
  NewLang.F1.Counterexample.Transition.field_change_keeps_enclosing_root_ptr_acquirable
  NewLang.F1.Counterexample.Transition.live_field_identity_cannot_be_acquired_through_root_only_erasure
  NewLang.F1.Reference.token_at_live_field_is_current
  NewLang.F1.Reference.acquire_requires_current_target
  NewLang.F1.Reference.acquire_implies_live_child_incarnation
  NewLang.F1.Reference.acquire_implies_live_parent_incarnation
  NewLang.F1.Reference.acquire_implies_live_governing_domain
  NewLang.F1.Reference.acquire_does_not_mint_access
  NewLang.F1.Reference.acquire_rejects_missing_stability
  NewLang.F1.Reference.acquire_rejects_missing_access
  NewLang.F1.Reference.acquire_rejects_wrong_path
  NewLang.F1.Reference.acquire_rejects_wrong_incarnation
  NewLang.F1.Reference.acquire_rejects_wrong_root_place
  NewLang.F1.Reference.acquire_rejects_wrong_root_incarnation
  NewLang.F1.Reference.acquire_rejects_wrong_domain
  NewLang.F1.Reference.acquire_rejects_wrong_site
  NewLang.F1.Reference.acquire_rejects_retargeted_field
  NewLang.F1.Reference.current_token_can_acquire
  NewLang.F1.Reference.field_replace_preserves_current_token
  NewLang.F1.Reference.field_replace_reacquires_with_post_evidence
  NewLang.F1.Reference.field_replace_preserves_token_at
  NewLang.F1.Reference.acquisition_does_not_bypass_current_dependency
  NewLang.F1.FixedLifetime.end_live_node_iff
  NewLang.F1.FixedLifetime.end_candidate_wellFormed
  NewLang.F1.FixedLifetime.end_preserves_wellFormed
  NewLang.F1.FixedLifetime.end_ends_every_fixed_incarnation
  NewLang.F1.FixedLifetime.end_ends_every_fixed_current_fact
  NewLang.F1.FixedLifetime.end_rejects_old_field_acquisition
  NewLang.F1.FixedLifetime.end_retains_identity_history
  NewLang.F1.FixedLifetime.ended_field_token_remains_recorded
  NewLang.F1.FixedLifetime.fresh_tree_restart_rejects_recorded_field_token
  NewLang.F1.FixedLifetime.end_then_fresh_restart_rejects_old_field_token
  NewLang.F1.FixedLifetime.end_rejects_missing_authority
  NewLang.F1.FixedLifetime.take_requires_ordinary_read
  NewLang.F1.FixedLifetime.destroy_requires_discardability
  NewLang.F1.FixedLifetime.end_preserves_other_node_identity
  NewLang.F1.FixedLifetime.end_preserves_domains
  NewLang.F1.FixedLifetime.take_returns_exact_value
  NewLang.F1.FixedLifetime.destroy_does_not_return_old_value
  NewLang.F1.FixedLifetime.take_has_f0_root_shadow
  NewLang.F1.FixedLifetime.destroy_has_f0_root_shadow
  NewLang.F1.FixedLifetime.take_root_occupancy_commutes_with_erasure
  NewLang.F1.FixedLifetime.destroy_root_occupancy_commutes_with_erasure
  NewLang.F1.FixedLifetime.take_parent_incarnation_ends_in_erasure
  NewLang.F1.FixedLifetime.destroy_parent_incarnation_ends_in_erasure
  NewLang.F1.FixedLifetime.take_rejects_returned_ended_fact_dependency
  NewLang.F1.FixedLifetime.end_rejects_external_ended_fact_dependency
  NewLang.F1.FixedLifetime.end_rejects_loose_ended_fact_dependency
  NewLang.F1.FixedLifetime.acquisition_does_not_mint_ending_authority
  NewLang.F1.Counterexample.Transition.live_nested_field_can_acquire
  NewLang.F1.Counterexample.Transition.field_token_rejects_wrong_path
  NewLang.F1.Counterexample.Transition.field_token_rejects_wrong_incarnation
  NewLang.F1.Counterexample.Transition.field_token_rejects_wrong_parent_place
  NewLang.F1.Counterexample.Transition.field_token_rejects_wrong_parent_incarnation
  NewLang.F1.Counterexample.Transition.field_token_rejects_wrong_site
  NewLang.F1.Counterexample.Transition.field_token_rejects_retargeting_to_sibling
  NewLang.F1.Counterexample.Transition.field_token_rejects_wrong_domain
  NewLang.F1.Counterexample.Transition.current_field_token_does_not_supply_stability_or_access
  NewLang.F1.Counterexample.Transition.omitting_liveness_accepts_inactive_root_table_data
  NewLang.F1.Counterexample.Transition.field_change_kills_value_fact_but_preserves_acquisition
  NewLang.F1.Counterexample.Transition.field_change_still_requires_new_acquisition_evidence
  NewLang.F1.Counterexample.Transition.sibling_change_does_not_retarget_field_token
  NewLang.F1.Counterexample.Transition.acquired_field_ref_cannot_launder_old_value_dependency
  NewLang.F1.Counterexample.Transition.independent_parent_take_and_destroy_are_legal
  NewLang.F1.Counterexample.Transition.parent_end_stales_field_token_without_changing_stored_fact
  NewLang.F1.Counterexample.Transition.field_access_does_not_grant_parent_ending_authority
  NewLang.F1.Counterexample.Transition.old_child_dependency_rejects_take_but_allows_destroy
  NewLang.F1.Counterexample.Transition.unchecked_take_preserves_dead_dependency_in_returned_value
  NewLang.F1.Counterexample.Transition.external_loose_dependency_rejects_both_parent_end_modes
  NewLang.F1.Counterexample.Transition.nondiscardable_root_can_be_taken_but_not_destroyed
  NewLang.F1.Counterexample.Transition.destroy_does_not_inherit_take_read_requirement
  NewLang.F1.Counterexample.Transition.fresh_same_site_tree_restart_does_not_revive_old_field_token
  NewLang.F1.Counterexample.Transition.historical_child_id_reuse_cannot_satisfy_restart_certificate
  NewLang.F1.Counterexample.Transition.same_field_token_survives_change_then_stales_after_parent_end
)
for declaration in "${declarations[@]}"; do
  printf '#print axioms %s\n' "$declaration" >> "$check_file"
done
if proof_output=$(lake env lean "$check_file" 2>&1); then
  :
else
  status=$?
  printf '%s\n' "$proof_output" >&2
  exit "$status"
fi
printf '%s\n' "$proof_output"
report_count=0
report=''
while IFS= read -r line; do
  report="${report:+$report }$line"
  case "$report" in
    *'depends on axioms: ['*)
      # Lean may wrap long theorem reports across several output lines.
      if [[ "$report" != *']' ]]; then continue; fi
      names="${report##*depends on axioms: [}"
      names="${names%]}"
      IFS=', ' read -r -a axiom_names <<< "$names"
      for name in "${axiom_names[@]}"; do
        case "$name" in
          propext|Classical.choice|Quot.sound) ;;
          *) echo "Unexpected proof axiom: $name" >&2; exit 1 ;;
        esac
      done
      ;;
    *'does not depend on any axioms') ;;
    *) echo "Unexpected Lean axiom report: $report" >&2; exit 1 ;;
  esac
  report_count=$((report_count + 1))
  report=''
done <<< "$proof_output"
if [ -n "$report" ] || [ "$report_count" -ne "${#declarations[@]}" ]; then
  echo 'Not all requested theorem axiom reports were produced.' >&2
  exit 1
fi
printf 'Verified %s theorem axiom reports (standard Lean logic only).\n' "$report_count"
